### PR TITLE
Feature/partial template

### LINKED ISSUE #10: Partial template CRUD
**Create partial template routes**
Add routes for crud operations, check trello for more information

### PR DESCRIPTION
**Pull request by elisa242003**
## Overview
This pull request implements the complete CRUD operations for the  `partialTemplate` model. It includes the creation of controller, service, DTOs, and module for managing partialTemplate.

## Changes
- **Controller:** Added `PartialTemplateController` to handle HTTP requests for creating, reading, updating, and deleting partialTemplate.
- **Service:** Added `PartialTemplateService` to contain the business logic for managing templates, including validation of foreign key references.
- **DTOs:** Added `CreatePartialTemplateDto` and `UpdatePartialTemplateDto` to define the structure of data for creating and updating partialTemplate
-  **Module:** Added `PartialTemplateModule` to encapsulate the template-related components.
- **Documentation:** Added JSDoc comments to all methods for better code documentation.

## Details
1. **PartialTemplateController**
   - `create()`: Handles POST requests to create a new partialTemplate.
   - `findAll()`: Handles GET requests to retrieve all partialTemplate.
   - `findOne()`: Handles GET requests to retrieve a partialTemplate by ID.
   - `update()`: Handles PATCH requests to update a partialTemplate by ID.
   - `remove()`: Handles DELETE requests to remove a partialTemplate by ID.

2. **PartialTemplateService**
   - `create()`:  Validates and creates a new PartialTemplate.
   - `findAll()`: Retrieves all PartialTemplates.
   - `findOne()`: Retrieves a PartialTemplate by ID.
   - `update()`: Updates a PartialTemplate by ID.
   - `remove()`: Deletes a PartialTemplate by ID.

3. **DTOS**
   - `CreatePartialTemplateDto()`:  Defines the data structure for creating a PartialTemplate.
   - `UpdatePartialTemplate()`: Defines the data structure for updating a PartialTemplates.

4. **Module**
   - `PartialTemplateModule`: Imports necessary modules and provides the `PartialTemplateController` and `PartialTemplateService`

5. **JSDoc Documentation**
   - Added detailed JSDoc comments to all methods and classes in the `PartialTemplateController` and `PartialTemplateService` for better understanding and maintenance.

## Related Issues
- Closes Partial template CRUD #10 

## Notes
- Ensure that related records (e.g., `PersonalData`, `Template`) are created in the database before testing the Template endpoints to avoid foreign key constraint errors.

Thank you for reviewing this pull request. I look forward to your feedback.

### CODE REVIEW

**Review by DiegoSHS — CHANGES_REQUESTED** [review]
The project version needs to be updated in the package.json to 0.1.1

**Review by coby111 — CHANGES_REQUESTED** [review]
All very well, just consider @DiegoSHS observations and identify your DTOs and document with the JSDoc syntax.

**Review by DiegoSHS — APPROVED** [review]
Well done, aproved changes, just waiting @Ana202016 to upload changes for creating a new release

**Review by coby111 — APPROVED** [review]
I have reviewed the changes proposed in this Pull Request and everything looks in order. Good job.

**Pull request merged**
